#!/usr/bin/env bash

# cd to repo root
cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
cd ..

echo ""
echo "=== Install System Dependencies ==="
./scripts/dependencies

echo ""
echo "=== Install ML Model Dependencies ==="
./model/setup.sh
